<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="8.0.21" />
    <PackageReference Include="Testcontainers.MsSql" Version="4.15.0" />
    <PackageReference Include="NSubstitute" Version="6.2.0" />
    <PackageReference Include="PdfPig" Version="0.1.16" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core\Portfolio.Core.csproj" />
    <ProjectReference Include="..\Application\Portfolio.Application.csproj" />
    <ProjectReference Include="..\Infrastructure\Portfolio.Infrastructure.csproj" />
    <ProjectReference Include="..\Portfolio\Portfolio.WebApi.csproj" />
  </ItemGroup>

</Project>
